### ISSUE TITLE
Outbreak field code (python branch)

### ISSUE THREAD

**Issue by lskatz** [tongzhouxu/mashpit#3]
Need to update database, probably the BioSample table.  Need to add an outbreak code field.

**Comment by lskatz** [comment]
E.g., 

2006MLGX6-1
20 - year
06 - month
ML - multilab (GA would have been Georgia, etc)
GX6 - "CDC code" for Listeria
-1 the ordinal

**Comment by tongzhouxu** [comment]
added in v0.6
